test: Add maude unit-testing framework
This doesn't test anything as of yet.

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 set -euo pipefail
 export PYTHONPYCACHEPREFIX='.build/'
+
+# TODO: Extract Maude running code from proof-gen.py and move the following
+# to test.py
+( maude test.maude  < /dev/null | grep 'result TestResult: passed' ) \
+    || { echo 'Maude unit-tests failed.';  exit 1 ; }
+
 mypy ./test.py
 exec ./test.py "$@"
